version: '3'

services:
 reviver-web:
    container_name: reviver-web
    image: dominikdoesdev/rv-website
    env_file:
      - .env
    restart: always
    ports:
      - 2224:2224
    build:
      context: .
      args:
        UPSTASH_API_KEY: ${UPSTASH_API_KEY}
